worlds:
    galaxy gates:
    - H999OVA79
    - QAAM7ORW3
    - OANGOBQ78
    - T99XCVSU3
    - X938T1I42
    - U44UFUUFB
    - BFFL0PSPV
    - 9992HVO7H
    - 599F01AUV
    - G445QUDJP
    - J989PWB8W
    - 7991GVPYP
    - BFFH3PWZK
    - 7991GVPHS
    - 793VG11JW
    - 844YJUROV
    - H999OVAO0
    - 8442GUNIA
    - I44I9U09J
    - L998NVCF3
    - V99VAVVSW
    - H999OVA5X
    - H999OVAW0
    - BFFL0PS77
    - 5993IVM0W
    - 9992HVOA2
    - H999OVANL
    - RFPLQFOKD
    - H999OVAOD
    - 593XI1YFI
    - K444PUFZC
    - 844YJUR7Z
    - PFLDMJ1M4
    - 5993IVM9O
    - 999EZ1CGS
    - H999OVAUT
    - S4Y9TZLUQ
    - T99XCVS1O
    - 7983JWNZ4
    - L998NVCPS
    - 3FFETP6CU
    - 999YKWMGD
    - H999OVAMT
    - H999OVAF3
    - W45TDTV9J
    - U44UFUUV8
    - X938T1IL3
    - L998NVC7C
    - 9992HVORZ
    - H999OVALE
    - 9992HVOC9
    - K4ZZPZPAP
    - H999OVA3Q
    - L998NVC6P
    - H999OVA4D
    - BFFL0PSJ2
    - H999OVA4I
    - 9992HVO1J
    - 5993IVM7H
    - K44G7U3PS
    - K444PUFGQ
    - FFFKZPU3B
    - H999OVAT6
    - X93QB164F
    - H999OVASR
    - H999OVACH
    - H999OVASM
    - G445QUDVG
    - U45SCTWOV
    - 5993IVM4I
    - 79WOMEFV9
    - 9992HVOL1
    - H999OVAL6
    - G445QUDW5
    - J997MVDCH
    - W44SDUXT1
    - FFFKZPU1R
    - I46K8X2ZH
    - T99XCVSQK
    - L998NVC16
    - NFHBPI0WJ
    - 9992HVO3Q
    - H999OVABU
    - QAM2Y6ZUI
    - ZFFFUP4A5
    - H999OVABP
    - T99XCVSNQ
    - H999OVA16
    - H999OVA8R
    - ZFFFUP4O8
    - 3FFETP6OL
    - U44UFUUXX
    - H999OVA9O
    - 844YJURV8
    - L998NVCTJ
    - X99WBVUZH
    - 5993IVMCH
    - 5993IVMSR
    - G445QUD96
    - AAALZNX7A
    - 5993IVM2Y
    - H999OVAPN
    - H999OVAXS
    - H999OVAYK
    - 5982IWOA7
    - 99X428M2S
    - T99TFVWL1
    - 9992HVOO5
    - 5993IVMLE
    - H999OVAHS
    - 9992HVO5X
