name = "kakusei-2-galaxy-gates"
author = "Dartis-Craft"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "909612837d30e0927f438a0fda168aeba5fe20b5d0f1c6aaa8b8d25032fecb3c"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
