name = "kakusei-2-galaxy-gates"
author = "Dartis-Craft"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3425724a7e53f632f46131222f3403c65d6cf8ced1f03a7d81bab764c2f961c6"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
